# ?????????????????????????????????????????????????????????????
#  eticksystem ? DEV profile
#
#  ??????: -Dspring.profiles.active=dev
#
#  ????????? ??????????. ???????? ????? ???????? ?
#  ?????? ???? ?? ????????? mail.eticksystem.com.
#  ???? ?? ?????? ??????? ? ?????? ?? Mailtrap (??. ????).
# ?????????????????????????????????????????????????????????????

# CORS ? ?????? localhost
app.cors.allowed-origins=http://localhost:3000

# MongoDB ? ????????? ????
spring.data.mongodb.uri=mongodb://localhost:27017/eticksystem

# JWT ? ??????? ?????? ??? ?????????? (??????? 32 ???????)
security.jwt.secret=dev_secret_key_change_me_32chars!!

# ??????????? ? ????????? ??? ???????
logging.level.root=INFO
logging.level.az.eticksystem=DEBUG
logging.level.org.springframework.security=DEBUG

# ?????? ? ? dev ?????????? ????????? (?????? ??? ???????)
server.error.include-message=always

# ?? Mail (???????? SMTP) ??????????????????????????????????????
# ?????????? ???????? ?????? ???? ? dev ? ?????? ???????.
# ??? ?????? ??? ???????? ???????? ?????.
spring.mail.host=mail.eticksystem.com
spring.mail.port=587
spring.mail.username=no-reply@eticksystem.com
spring.mail.password=pLs5Wt4O0k6C6c2ZlX6mZGv5V
spring.mail.properties.mail.smtp.ssl.trust=mail.eticksystem.com