# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/tickit}

# JWT
security.jwt.secret=change_this_dev_secret_key_very_long
security.jwt.expiration-ms=86400000

# Logging (optional)
logging.level.org.springframework.security=TRACE

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
server.tomcat.max-http-form-post-size=50MB

server.error.include-message=always

spring.mail.host=mail.eticksystem.com
spring.mail.port=587
spring.mail.username=no-reply@eticksystem.com
spring.mail.password=pLs5Wt4O0k6C6c2ZlX6mZGv5V
spring.mail.properties.mail.smtp.auth=true

# ??????? ????????? ??????? ???????? ???? ???????????? (??? ??????????? ?????)
spring.mail.properties.mail.smtp.ssl.trust=*

# ?????????????? ????????? ??? ????????????
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.starttls.enable=true
